INSERT INTO comidas VALUES (1,1,1,"Guisado de costillas, Calamar romana, Fruta","Bocadillo de york","Sopa de fideos, Hamburguesas, Lácteo");
INSERT INTO comidas VALUES (2,1,2,"Potaje de garbanzos, Muslo de pollo, Fruta","Bocadillo de pavo","Guisantes con jamón, Marrajo, Fruta");
INSERT INTO comidas VALUES (3,1,3,"Tortilla de patatas, Lomo con queso, Lácteo","Bocadillo de mortadela","Zarangollo murciano, Pescado blanco en salsa verde, Fruta");
INSERT INTO comidas VALUES (4,1,4,"Espaguettis con atún, Bacalao bilbaína, Fruta","Bocadillo de salchichón","Crema de puerros, Pechulga de pollo, Lácteo");
INSERT INTO comidas VALUES (5,1,5,"Arroz 3 delicias, Alas de pollo, Postre casero","Bocadillo de nocilla","Moje manchego, Escalope de lomo, Fruta");
INSERT INTO comidas VALUES (6,1,6,"Macarrones con tomate y bacon, Merluza a la vasca, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (7,1,7,"Sopa castellana, Salchichas con pisto, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (8,2,1,"Macarrones boloñesa, Tilapia al horno, Fruta","Bocadillo de chorizo","Tortilla con salteado de verduras, Magra en salsa, Lácteo");
INSERT INTO comidas VALUES (9,2,2,"Fideuá de marisco, Pechuga de pollo plancha, Fruta","Bocadillo de york","Ensaladilla rusa, Marrajo con tomate, Fruta");
INSERT INTO comidas VALUES (10,2,3,"Arroz caldoso, Filete de merluza, Lácteo","Bocadillo de salami","Espinacas salteadas, Salchicas encebolladas, Fruta");
INSERT INTO comidas VALUES (11,2,4,"Crema de calabacín, Albóndigas jardinera, Fruta","Bocadillo de mortadela","Puré de patatas con york y queso, Filete de bacalao al horno, Lácteo");
INSERT INTO comidas VALUES (12,2,5,"Lentejas estofadas, Perca al gusto del chef, Postre casero","Bocadillo de paté","Hervido, Pizza, Fruta");
INSERT INTO comidas VALUES (13,2,6,"Sopa de marisco, Pollo asado, Lácteo","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (14,2,7,"Gazpacho manchego, Pescado blanco a la gallega, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (15,3,1,"Arroz blanco con tomate, Lasaña, Fruta","Bocadillo de chopped","Judías verdes con jamón, Pechuga plancha, Lácteo");
INSERT INTO comidas VALUES (16,3,2,"Huevos a la flamenca, Rabas de calamar, Fruta","Bocadillo de pavo","Crema de calabaza, Alas de pollo, Fruta");
INSERT INTO comidas VALUES (17,3,3,"Patatas bravas, Hamburguesas, Lácteo","Bocadillo de york","Moje, Tilapia en salsa, Fruta");
INSERT INTO comidas VALUES (18,3,4,"Arroz a banda, Cordon blue, Fruta","Bocadillo de salchichón","Calabacín gratinado, Pescadilla, Lácteo");
INSERT INTO comidas VALUES (19,3,5,"Espaguettis carbonara, Caldereta de cerdo, Postre casero","Bocadillo de nocilla","Ensalada césar, Pizza, Fruta");
INSERT INTO comidas VALUES (20,3,6,"Tortilla de patatas, Ternera estofada, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (21,3,7,"Sopa de pollo, Albóndigas, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (22,4,1,"Macarrones con atún, Salchichas, Fruta","Bocadillo de york y queso","Crema de verduras, Palitos de merluza, Lácteo");
INSERT INTO comidas VALUES (23,4,2,"Arroz negro, Caballa al horno, Fruta","Bocadillo de pavo","Tortilla francesa con patatas, Pechuga empanada, Fruta");
INSERT INTO comidas VALUES (24,4,3,"Sopa de cocido, Carne de cocido, Fruta","Bocadillo de mortadela","Coliflor gratinada, Alitas de pollo, Fruta");
INSERT INTO comidas VALUES (25,4,4,"Menestra, Guiso de costillas, Fruta","Bocadillo de salchichón","Sopa de boda, Escalope con patatas, Lácteo");
INSERT INTO comidas VALUES (26,4,5,"Lentejas, Merluza en salsa verde, Postre casero","Bocadillo de nocilla","Pisto con huevo, Pizza, Fruta");
INSERT INTO comidas VALUES (27,4,6,"Canelones, Pescado blanco al horno, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua o refresco");
INSERT INTO comidas VALUES (28,4,7,"Patatas y huevos revueltos, Pechuga plancha, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua o refresco");
INSERT INTO comidas VALUES (29,5,1,"Fideos a la catalana, Merluza al limón, Fruta","Bocadillo de chorizo","Asadillo de pimientos, Lomo adobado, Lácteo");
INSERT INTO comidas VALUES (30,5,2,"Tortilla de patatas, Hamburguesas, Fruta","Bocadillo de nocilla","Puré de verduras, Calamar en salsa americana, Fruta");
INSERT INTO comidas VALUES (31,5,3,"Judías verdes con jamón, Guiso de ternera, Lácteo","Bocadillo de york y queso","Sopa con fideos, Chuleta de sajonia, Fruta");
INSERT INTO comidas VALUES (32,5,4,"Macarrones napolitana, Pollo asado, Fruta","Bocadillo de mortadela","Lasaña, Empanadillas, Lácteo");
INSERT INTO comidas VALUES (33,5,5,"Paella mixta, Rabas de calamar, Postre casero","Bocadillo de paté","Champiñones gratinados, Alas de pollo, Fruta");
INSERT INTO comidas VALUES (34,5,6,"Patatas a la riojana, Pinchos morunos, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (35,5,7,"Olla de aldea, Tilapia, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (36,6,1,"Espaguettis boloñesa, Pescadilla, Fruta","Bocadillo de pavo","Moje, Salchicas blancas, Lácteo");
INSERT INTO comidas VALUES (37,6,2,"Crema de calabaza, Pollo al ajillo, Fruta","Bocadillo de chorizo","Guisantes con jamón, Merluza menier, Fruta");
INSERT INTO comidas VALUES (38,6,3,"Lentejas estofadas, Tilapia, Lácteo","Bocadillo de salchichón","Menestra, Chuletas de lomo, Fruta");
INSERT INTO comidas VALUES (39,6,4,"Atascaburras, Albóndigas con tomate, Fruta","Bocadillo de chopped","Revuelto de champiñón con gambas, Cordon blue, Lácteo");
INSERT INTO comidas VALUES (40,6,5,"Arroz a la milanesa, Bacalao al horno con salsa, Postre casero","Bocadillo de nocilla","Berenjenas parmesana, Nuggets de pollo, Fruta");
INSERT INTO comidas VALUES (41,6,6,"Lasaña de verduras, Magra con tomate, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (42,6,7,"Huevos fritos con bacon, Salmón con crema de ajo, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
