INSERT INTO comidas VALUES (1,1,1,"Ensalada campera, Muslo de pollo asado, Fruta","Bocadillo de queso","Sopa juliana, Marrajo, Lácteo");
INSERT INTO comidas VALUES (2,1,2,"Potaje de garbanzos, Calamar a la romana, Fruta","Bocadillo de pavo","Guisantes con jamón, Hamburguesas, Fruta");
INSERT INTO comidas VALUES (3,1,3,"Tortilla de patatas, Lomo con queso, Lácteo","Bocadillo de atún","Revuelto de ajetes, Pescado blanco en salsa verde, Fruta");
INSERT INTO comidas VALUES (4,1,4,"Espaguettis carbonara, Fogonero bilbaína, Fruta","Bocadillo de salchichón","Crema de puerros, Cordon blue, Lácteo");
INSERT INTO comidas VALUES (5,1,5,"Salmorejo cordobés, Alas de pollo marinadas, Postre casero","Bocadillo de nocilla","Champiñón al ajillo, Tilapia en salsa de pimientos, Fruta");
INSERT INTO comidas VALUES (6,1,6,"Arroz 3 delicias, Merluza a la vasca, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (7,1,7,"Sopa castellana, Salchichas con pisto, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (8,2,1,"Macarrones boloñesa, Tilapia al horno, Fruta","Bocadillo de chorizo","Tortilla con salteado de verduras, Magra en salsa, Lácteo");
INSERT INTO comidas VALUES (9,2,2,"Crema de calabacín, Pechuga de pollo a la plancha, Fruta","Bocadillo de york","Ensaladilla rusa, Marrajo con tomate, Fruta");
INSERT INTO comidas VALUES (10,2,3,"Arroz caldoso, Filete de merluza, Lácteo","Bocadillo de salami","Espinacas salteadas, Salchicas encebolladas, Fruta");
INSERT INTO comidas VALUES (11,2,4,"Fideuá de marisco, Albóndigas jardinera, Fruta","Bocadillo de queso","Puré de patatas con york y queso, Filete de bacalao al horno, Lácteo");
INSERT INTO comidas VALUES (12,2,5,"Lentejas estofadas, Perca al gusto del chef, Postre casero","Bocadillo de paté","Hervido, Pizza, Fruta");
INSERT INTO comidas VALUES (13,2,6,"Ensalada de pasta, Pollo asado, Lácteo","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (14,2,7,"Gazpacho manchego, Pescado blanco a la gallega, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (15,3,1,"Moje manchego, Lasaña de carne, Fruta","Bocadillo de chopped","Judías verdes con jamón, Tilapia en salsa, Lácteo");
INSERT INTO comidas VALUES (16,3,2,"Huevos a la flamenca, Rabas de calamar, Fruta","Bocadillo de chorizo","Crema de calabaza, Alas de pollo, Fruta");
INSERT INTO comidas VALUES (17,3,3,"Gazpacho Andaluz, Hamburguesas, Lácteo","Bocadillo de york","Ensalada de patata con huevo y atún, Pescadilla, Fruta");
INSERT INTO comidas VALUES (18,3,4,"Arroz a banda, Fogonero a la vizcaína, Fruta","Bocadillo de salchichón","Calabacín gratinado, San jacobos, Lácteo");
INSERT INTO comidas VALUES (19,3,5,"Espaguettis carbonara, Lomo en salsa, Postre casero","Bocadillo de queso","Pisto manchego, Pizza, Fruta");
INSERT INTO comidas VALUES (20,3,6,"Tortilla de patatas, Platija al horno, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (21,3,7,"Ensalada de palitos, Albóndigas, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (22,4,1,"Macarrones con atún, Salchicas, Fruta","Bocadillo de york y queso","Crema de puerros, Pescaíto frito, Lácteo");
INSERT INTO comidas VALUES (23,4,2,"Arroz negro, Caballa al horno, Fruta","Bocadillo de pavo","Tortilla francesa con patatas, Pechuga empanada, Fruta");
INSERT INTO comidas VALUES (24,4,3,"Cocido madrileño, Carne de cocido, Fruta","Bocadillo de atún","Coliflor gratinada, Marrajo a la marinera, Fruta");
INSERT INTO comidas VALUES (25,4,4,"Guisado de costillas, Merluza en salsa verde, Fruta","Bocadillo de salchichón","Mojete manchego, Escalope con patatas, Lácteo");
INSERT INTO comidas VALUES (26,4,5,"Ensaladilla rusa, Caldereta de cerdo, Postre casero","Bocadillo de nocilla","Pisto con huevo, Pizza, Fruta");
INSERT INTO comidas VALUES (27,4,6,"Canelones, Pescado blanco al horno, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua o refresco");
INSERT INTO comidas VALUES (28,4,7,"Patatas y huevos revueltos, Chorizos, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua o refresco");
INSERT INTO comidas VALUES (29,5,1,"Fideos a la catalana, Merluza al limón, Fruta","Bocadillo de chorizo","Asadillo de pimientos, Pechuga de pollo a la plancha, Lácteo");
INSERT INTO comidas VALUES (30,5,2,"Tortilla de patatas, Hamburguesas, Fruta","Bocadillo de nocilla","Puré de verduras, Calamar en salsa americana, Fruta");
INSERT INTO comidas VALUES (31,5,3,"Guisado de ternera, Tilapia en salsa de esparragos, Lácteo","Bocadillo queso","Sopa con fideos, Redondo de pavo relleno, Fruta");
INSERT INTO comidas VALUES (32,5,4,"Macarrones napolitana, Costillas asadas, Fruta","Bocadillo de mortadela","Ensalada de palitos, Marrajo en salsa meuniere, Lácteo");
INSERT INTO comidas VALUES (33,5,5,"Paella mixta, Rabas de calamar, Postre casero","Bocadillo de paté","Champiñones gratinados, Cordon blue, Fruta");
INSERT INTO comidas VALUES (34,5,6,"Patatas a la riojana, Pinchos morunos, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (35,5,7,"Lasaña, Platija al horno, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (36,6,1,"Espaguettis carbonara, Pescadilla al horno, Fruta","Bocadillo de queso","Moje, Salchicas blancas al vino, Lácteo");
INSERT INTO comidas VALUES (37,6,2,"Salmorejo, Pollo al ajillo, Fruta","Bocadillo de chorizo","Guisantes con jamón, Merluza plancha, Fruta");
INSERT INTO comidas VALUES (38,6,3,"Lentejas estofadas, Tilapia al horno, Lácteo","Bocadillo de atún","Menestra, Lomo con patatas fritas, Fruta");
INSERT INTO comidas VALUES (39,6,4,"Ensalada césar, Albóndigas con tomate, Fruta","Bocadillo de chopped","Revuelto de ajetes, Flamenquines, Lácteo");
INSERT INTO comidas VALUES (40,6,5,"Judías pintas, Bacalao al horno con salsa, Postre casero","Bocadillo de nocilla","Arroz 3 delicias, Rollitos de primavera, Fruta");
INSERT INTO comidas VALUES (41,6,6,"Ensalada de pasta, Magra con tomate, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
INSERT INTO comidas VALUES (42,6,7,"Huevos fritos con bacon, Salmón con crema de ajo, Fruta","Zumo de frutas y bollería embolsada","Picnic: Bocadillo caliente, bocadillo frío, fruta, agua");
